---
title: "VMS QC report"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

<!--
<style>
#TOC {
  background:url("http://www.ices.dk/_layouts/15/1033/images/icesimg/iceslogo.png") ;
  background-size: contain;
  padding-top: 100px !important;
  background-repeat: no-repeat;
  position: fixed;
  font-size: 12px;
  left: 0;
  top: 0;
  width: 200px;
  height: 80%;
  overflow:auto;
}
</style>
-->


```{r setup, eval = TRUE, echo = FALSE, cache = FALSE, message = FALSE}
library(knitr)
library(dplyr)
library(tidyr)
library(DT)
library(plotly)
library(leaflet)
library(sf)

opts_chunk$set(
  comment = NA,
  warning = FALSE,
  message = FALSE,
  error = FALSE,
  echo = FALSE,
  eval = FALSE
)

options(digits = 4)
```

# VMS data submission QC

```{r child = 'report_vms_discrete.Rmd'}
```

```{r child = 'report_vms_continuous.Rmd'}
```

```{r child = 'report_vms_timeseries.Rmd'}
```

```{r child = 'report_vms_spatial.Rmd'}
```

# Logbook data submission QC

```{r child = 'report_logbook_discrete.Rmd', eval = TRUE}
```